language: node_js
node_js: stable

install:
- npm install

script:
- npm run-script build

after_script:
- cd ./dist
- git init
- git config user.name "rjgeek"
- git config user.email "rxl635@student.bham.ac.uk"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/rjgeek/paper-manager-vue.git
